CREATE TABLE [dbo].[Quarter]
(
	[Id]            INT IDENTITY(1,1) NOT FOR REPLICATION NOT NULL, 
    [Code]          NVARCHAR(50) NOT NULL, 
    [StartDate]     DATE NOT NULL, 
    [EndDate]       DATE NOT NULL,
    [DateCreated]   DATETIME NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_Quarter] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (PAD_INDEX = OFF, DATA_COMPRESSION = PAGE )
) 

GO 

CREATE UNIQUE INDEX [IX_Quarter_Code] ON [dbo].[Quarter] ([Code] ASC) WITH (PAD_INDEX = OFF, DATA_COMPRESSION = PAGE )
GO

CREATE UNIQUE INDEX [IX_Quarter_StartDate_EndDate] ON [dbo].[Quarter] ([StartDate] ASC, [EndDate] ASC) WITH (PAD_INDEX = OFF, DATA_COMPRESSION = PAGE )
GO
