CREATE TABLE [dbo].[Week]
(
	[Id]            INT IDENTITY(1,1) NOT FOR REPLICATION NOT NULL, 
	[QuarterId]     INT NOT NULL, 
	[Code]          NVARCHAR(50) NOT NULL, 
	[StartDate]     DATE NOT NULL, 
	[EndDate]       DATE NOT NULL,
	[DateCreated]   DATETIME NOT NULL DEFAULT SYSUTCDATETIME(),
	CONSTRAINT [PK_Week] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (PAD_INDEX = OFF, DATA_COMPRESSION = PAGE ),
	CONSTRAINT [FK_Week_Quarter] FOREIGN KEY ([QuarterId]) REFERENCES [dbo].[Quarter] ([Id]) ON DELETE CASCADE
)

GO

CREATE UNIQUE INDEX [IX_Week_Code] ON [dbo].[Week] ([Code] ASC) WITH (PAD_INDEX = OFF, DATA_COMPRESSION = PAGE )

GO 

CREATE UNIQUE INDEX [IX_Week_StartDate_EndDate] ON [dbo].[Week] ([StartDate] ASC, [EndDate] ASC) WITH (PAD_INDEX = OFF, DATA_COMPRESSION = PAGE )