<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Vicgital.Grpc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vicgital.Calendar.Application\Vicgital.Calendar.Application.csproj" />
    <ProjectReference Include="..\Vicgital.Calendar.Infrastructure\Vicgital.Calendar.Infrastructure.csproj" />
    <ProjectReference Include="..\Vicgital.Calendar.Service.Definition\Vicgital.Calendar.Service.Definition.csproj" />
  </ItemGroup>

</Project>
