<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Vicgital.Application.Shared" />
    <PackageReference Include="Vicgital.Core.Caching.InMemory" />
  </ItemGroup>  

  <ItemGroup>
    <ProjectReference Include="..\Vicgital.Calendar.Domain\Vicgital.Calendar.Domain.csproj" />
  </ItemGroup>

</Project>
