<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>Vicgital.Calendar.Service.Definition</AssemblyName>
		<PackageId>Vicgital.Calendar.Service.Definition</PackageId>
		<Version>2.1.0</Version>
		<Authors>Vicgital</Authors>
		<RepositoryUrl>https://github.com/vicgital/Vicgital.Calendar.Service</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageDescription>GRPC Service Definition for Calendar Service</PackageDescription>
		<IncludeGoogleApiCommonProtos>true</IncludeGoogleApiCommonProtos>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Api.CommonProtos" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Core.Api" />
		<PackageReference Include="Grpc.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>


	<ItemGroup>
		<Protobuf Include="protos\calendar.proto" GrpcServices="Both" />
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="protos\" />
	</ItemGroup>

</Project>
