syntax = "proto3";
option csharp_namespace = "Vicgital.Calendar.Service.Definition";

import "google/type/date.proto";

service Calendar {

	rpc GetQuarter (QuarterRequest) returns (QuarterModel);
	rpc GetQuartersByYear (YearRequest) returns (QuartersReply);
	rpc GetQuarterByDate (DateRequest) returns (QuarterModel);
	rpc CreateQuartersByYear (YearRequest) returns (QuartersReply);

	rpc GetWeek (WeekRequest) returns (WeekModel);
	rpc GetWeeksByQuarter (QuarterRequest) returns (WeeksReply);
	rpc GetWeekByDate (DateRequest) returns (WeekModel);
	rpc CreateWeeksByQuarter (CreateWeeksByQuarterRequest) returns (WeeksReply);

	rpc GetFortnight (FortnightRequest) returns (FortnightModel);
	rpc GetFortnightsByYear (YearRequest) returns (FortnightsReply);
	rpc GetFortnightByDate (DateRequest) returns (FortnightModel);
	rpc CreateFortnightsByYear (YearRequest) returns (FortnightsReply);


}

message DateRequest {
	google.type.Date date = 1;
}

message WeekRequest {
	oneof identifier {
		int32 id = 1;
		string code = 2;
	}
}

message CreateWeeksByQuarterRequest {
	string quarterCode = 1;
}

message WeeksReply {
	repeated WeekModel weeks = 1;
}

message WeekModel {
	int32 id = 1;
	string code = 2;
	google.type.Date startDate = 3;
	google.type.Date endDate = 4;
}

message YearRequest {
	int32 year = 1;
}

message QuarterRequest {
	oneof identifier {
		int32 id = 1;
		string code = 2;
	}
}

message QuartersReply {
	repeated QuarterModel quarters = 1;
}

message QuarterModel {
	int32 id = 1;
	string code = 2;
	google.type.Date startDate = 3;
	google.type.Date endDate = 4;
}


message FortnightRequest {
	oneof identifier {
		int32 id = 1;
		string code = 2;
	}
}

message FortnightsReply {
	repeated FortnightModel fortnights = 1;
}

message FortnightModel {
	int32 id = 1;
	string code = 2;
	google.type.Date startDate = 3;
	google.type.Date endDate = 4;
}