<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Vicgital.Data.Sql" />
	</ItemGroup>
	

  <ItemGroup>
    <ProjectReference Include="..\Vicgital.Calendar.Application\Vicgital.Calendar.Application.csproj" />
    <ProjectReference Include="..\Vicgital.Calendar.Domain\Vicgital.Calendar.Domain.csproj" />
  </ItemGroup>

</Project>
